name: flutter_hub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  transparent_image: 1.0.0
  http: 0.12.2
  pedantic: 1.9.2
  webview_flutter: ^1.0.5

  flutter_launcher_icons: ^0.8.1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icongithub.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icongithub.png
